### ISSUE TITLE
glyphicon in grid view

### ISSUE THREAD

**Issue by celsoft** [hail812/yii2-adminlte3#2]
how to fix?
![Clip2net_200602115019](https://user-images.githubusercontent.com/5567863/83500308-40c01a00-a4c7-11ea-990e-7a75d8f9003e.png)

**Comment by jashirouprotips** [comment]
Hi @celsoft,

You are using Glyphicon Assets from Bootstrap 3.3. Since Bootstrap 4 this library icons was removed.

You should use FontAwesome 5.13 free library attached to this AdminLTE3 version.

Check it out and try next link:
https://fontawesome.com/icons?d=gallery&m=free

==========================================================
### UPDATE
==========================================================

**FIRST:**
In your project find "ActionColumn.php" into the next path:
`@vendor/yiisoft/yii2/grid/`

**SECOND:**
Then in the next lines change the icon names like this:

```
145        $this->initDefaultButton('view', 'eye');
146        $this->initDefaultButton('update', 'pencil-alt');
147        $this->initDefaultButton('delete', 'trash',
```

**THIRD AND LAST STEP:**
Find the line **182** and chage:

**CHANGE** `"glyphicon glyphicon-$iconName"`
**TO:** `"fas fa-$iconName"`

And that's all...

Hope works to you because did work to me.
